package:
  name: planemo
  version: "0.29.1"

source:
  fn: planemo-0.29.1.tar.gz
  url: https://pypi.python.org/packages/79/41/4d65672ebe325f7c101366521d9b9d6d2b1e5b828953985da9509f8dd96f/planemo-0.29.1.tar.gz
  md5: 06c8b488ed86e66fc88adcad551bb50a

build:
  preserve_egg_dir: True
  skip: True # [py3k]
  entry_points:
    - planemo=planemo.cli:planemo

  number: 0

requirements:
  build:
    - python
    - six
    - click
    - pyaml
    - bioblend >=0.8.0
    - jinja2
    - virtualenv
    - galaxy-lib >=16.7.10
    - aenum

  run:
    - python
    - six
    - click
    - pyaml
    - bioblend >=0.8.0
    - jinja2
    - virtualenv
    - galaxy-lib >=16.7.10
    - aenum

test:
  # Python imports
  imports:
    - planemo
    - planemo.commands
    - planemo.cwl
    - planemo.cwl.cwl2script
    - planemo.database
    - planemo.engine
    - planemo.galaxy
    - planemo.galaxy.test
    - planemo.linters
    - planemo.reports
    - planemo.shed
    - planemo.shed2tap
    - planemo.test
    - planemo.xml

  commands:

    - planemo --help

about:
  home: https://github.com/galaxyproject/planemo
  license: Academic Free License (AFL)
  summary: 'Command-line utilities to assist in building tools for the Galaxy project (http://galaxyproject.org/).'
  license_family: Apache
